import { readFileSync, writeFileSync } from 'fs'

import { queryCodeMonkey } from '@openai'
import { combinePromptAndCode } from '@openai/util'

const main = async () => {
    const entityName = process.argv[2]
    const autoGeneratedCode = readFileSync(
        `./generated-entities/${entityName}.ts`,
        'utf-8'
    )

    const prompt = combinePromptAndCode('./src/openai/jobs/transform-entities/prompt.md', autoGeneratedCode)
    const codeMonkeyResponse = await queryCodeMonkey(prompt)

    writeFileSync(`./src/entities/${entityName}.ts`, codeMonkeyResponse)
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .then(() => {
        process.exit(0)
    })
